// swift-tools-version:5.9
// Generated by scripts/release/swift-dist.mjs from packages/ios-livekit at version 0.1.0-beta.2.
// Don't edit here: change the monorepo and release again.
import PackageDescription

// The native LiveKit `VoiceSource` (docs/audio-pipeline.md, *Native LiveKit*).
// Its own package, not a product of packages/ios: SwiftPM resolves every
// declared dependency of a package, so putting LiveKit there would make every
// SinuaView consumer fetch the SDK and its WebRTC binary even if they never link
// this. The SDK-free logic (`LiveKitAgentTracker`) lives in SinuaVoice and
// is tested there; this package is only the Room/track glue.
let package = Package(
    name: "SinuaLiveKit",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "SinuaLiveKit", targets: ["SinuaLiveKit"])
    ],
    dependencies: [
        .package(url: "https://github.com/sinua-dev/sinua-swift", exact: "0.1.0-beta.2"),
        .package(url: "https://github.com/livekit/client-sdk-swift.git", from: "2.17.0"),
    ],
    targets: [
        .target(
            name: "SinuaLiveKit",
            dependencies: [
                .product(name: "SinuaVoice", package: "sinua-swift"),
                .product(name: "LiveKit", package: "client-sdk-swift"),
            ],
            path: "Sources/SinuaLiveKit"
        )
    ]
)
